!===============================================================================
! AGENTIC 0D CONSTANT-VOLUME IGNITION CAMPAIGN INTERFACE
!===============================================================================
!
! One invocation creates exactly one self-contained NRG case from a namelist
! generated by campaign_generator_0d.py.  A homogeneous constant-volume reactor
! is represented by a very small 1-D Cartesian domain with uniform initial
! conditions and closed adiabatic slip walls.
!
! The interface is intentionally deterministic:
!   * case identity and scientific fingerprint come from the campaign manifest;
!   * an existing case directory is never overwritten;
!   * run lifetime is delegated to run_control_class;
!   * chemistry species are resolved by name, not mechanism order;
!   * reactor_history contains T, p, rho and every species mass fraction.
!
! The first command-line argument may specify the input namelist.  Without an
! argument, setup_input.nml in the current directory is used.
!===============================================================================

program package_interface

    use, intrinsic :: iso_c_binding, only : c_char, c_int, c_null_char
    use kind_parameters
    use global_data
    use computational_domain_class
    use chemical_properties_class
    use thermophysical_properties_class
    use solver_options_class
    use computational_mesh_class
    use mpi_communications_class
    use data_manager_class
    use boundary_conditions_class
    use field_scalar_class
    use field_vector_class
    use data_save_class
    use data_io_class
    use post_processor_manager_class
    use run_control_class

    implicit none

#ifdef WIN
    interface
        function c_chdir(path) bind(C, name='_chdir') result(status)
            import :: c_char, c_int
            character(kind=c_char), intent(in) :: path(*)
            integer(c_int) :: status
        end function c_chdir
    end interface
#else
    interface
        function c_chdir(path) bind(C, name='chdir') result(status)
            import :: c_char, c_int
            character(kind=c_char), intent(in) :: path(*)
            integer(c_int) :: status
        end function c_chdir
    end interface
#endif

    !--------------------------------------------------------------------------
    ! NRG objects
    !--------------------------------------------------------------------------
    type(computational_domain)                :: problem_domain
    type(data_manager)                        :: problem_data_manager
    type(mpi_communications)                  :: problem_mpi_support
    type(chemical_properties),       target   :: problem_chemistry
    type(thermophysical_properties), target   :: problem_thermophysics
    type(solver_options)                      :: problem_solver_options
    type(computational_mesh),        target   :: problem_mesh
    type(boundary_conditions),       target   :: problem_boundaries
    type(field_scalar_cons),         target   :: p, T, rho
    type(field_vector_cons),         target   :: v, Y
    type(post_processor_manager)              :: problem_post_proc_manager
    type(data_io)                              :: problem_data_io
    type(data_save)                            :: problem_data_save
    type(run_control)                          :: problem_run_control

    !--------------------------------------------------------------------------
    ! Campaign / case identity
    !--------------------------------------------------------------------------
    character(len=32)  :: case_id
    character(len=32)  :: case_fingerprint
    character(len=128) :: case_directory
    character(len=256) :: case_label
    character(len=80)  :: campaign_id
    character(len=256) :: results_root
    character(len=64)  :: numerical_variant

    namelist /case_config/ case_id, case_fingerprint, case_directory, &
        case_label, campaign_id, results_root, numerical_variant

    !--------------------------------------------------------------------------
    ! Reactor definition
    !--------------------------------------------------------------------------
    character(len=32) :: reactor_type
    integer           :: cells_number_x
    real(dp)          :: cell_length_x

    namelist /reactor_config/ reactor_type, cells_number_x, cell_length_x

    !--------------------------------------------------------------------------
    ! Mixture and thermodynamic initial state
    !--------------------------------------------------------------------------
    real(dp) :: hydrogen_mole_percent
    real(dp) :: n2_o2_molar_ratio
    real(dp) :: initial_temperature
    real(dp) :: initial_pressure

    namelist /mixture_config/ hydrogen_mole_percent, n2_o2_molar_ratio, &
        initial_temperature, initial_pressure

    !--------------------------------------------------------------------------
    ! Physics / numerics
    !--------------------------------------------------------------------------
    character(len=32) :: mechanism_id
    character(len=32) :: solver_id
    real(dp)          :: initial_time_step
    logical           :: cfl_enabled
    real(dp)          :: cfl_coefficient

    character(len=64) :: thermo_data_file
    character(len=64) :: transport_data_file

    namelist /physics_config/ mechanism_id, thermo_data_file, &
    transport_data_file, solver_id, initial_time_step, &
    cfl_enabled, cfl_coefficient

    !--------------------------------------------------------------------------
    ! Run control
    !--------------------------------------------------------------------------
    character(len=24) :: termination_mode
    real(dp)          :: final_time_ms
    real(dp)          :: wall_time_limit_s
    real(dp)          :: wall_time_reserve_s

    namelist /run_control_config/ termination_mode, final_time_ms, &
        wall_time_limit_s, wall_time_reserve_s

    !--------------------------------------------------------------------------
    ! Output
    !--------------------------------------------------------------------------
    real(dp) :: postprocess_interval_us
    real(dp) :: field_save_interval_us
    real(dp) :: checkpoint_interval_us
    logical  :: save_spatial_fields

    namelist /output_config/ postprocess_interval_us, &
        field_save_interval_us, checkpoint_interval_us, save_spatial_fields

    !--------------------------------------------------------------------------
    ! Derived configuration and local variables
    !--------------------------------------------------------------------------
    character(len=64)   :: mechanism_name
    character(len=64)   :: mech_file
    character(len=64)   :: thermo_file
    character(len=64)   :: transdata_file
    character(len=32)   :: solver_name
    character(len=1024) :: config_file
    character(len=1024) :: work_dir
    character(len=2048) :: command
    character(len=512)  :: iomsg
    character(len=64)   :: specie_name
    character(len=64)   :: field_name

    integer :: io_unit, log_unit, ierr, command_status, exit_status
    integer :: arg_count
    integer :: spec
    integer :: h2_index, o2_index, n2_index
    integer :: utter_loop(3,2), inner_loop(3,2)
    integer :: transducer_area(3,2), transducer_cell(3)
    integer :: operations_number
    real(dp):: domain_length
    real(dp):: nu, phi
    real(dp):: effective_field_save_interval
    logical :: stop_flag

    !--------------------------------------------------------------------------
    ! Defaults. Campaign files normally override every relevant quantity.
    !--------------------------------------------------------------------------
    case_id                  = 'R000001'
    case_fingerprint         = ''
    case_directory           = 'R000001'
    case_label               = ''
    campaign_id              = '0D_CV_validation'
    results_root             = '0D_cases'
    numerical_variant        = 'base'

    reactor_type             = 'constant_volume'
    cells_number_x           = 2
    cell_length_x            = 1.0e-4_dp

    hydrogen_mole_percent    = 20.0_dp
    n2_o2_molar_ratio        = 3.762_dp
    initial_temperature      = 1500.0_dp
    initial_pressure         = 101325.0_dp

    mechanism_id             = 'keromnes'
    solver_id                = 'cpm'
    initial_time_step        = 1.0e-8_dp
    cfl_enabled              = .false.
    cfl_coefficient          = 0.25_dp

    termination_mode         = 'wall_time'
    final_time_ms            = 0.03_dp
    wall_time_limit_s        = 3600.0_dp
    wall_time_reserve_s      = 30.0_dp

    postprocess_interval_us  = 0.1_dp
    field_save_interval_us   = 5.0_dp
    checkpoint_interval_us   = 25.0_dp
    save_spatial_fields      = .true.
    
    thermo_data_file        = 'COMMON_THERMO.txt'
    transport_data_file     = 'COMMON_TRANSDATA.txt'

    !--------------------------------------------------------------------------
    ! Read configuration. Group order in the file is irrelevant.
    !--------------------------------------------------------------------------
    config_file = 'setup_input.nml'
    arg_count = command_argument_count()
    if (arg_count >= 1) then
        call get_command_argument(1, config_file)
        if (len_trim(config_file) == 0) config_file = 'setup_input.nml'
    end if

    open(newunit=io_unit, file=trim(config_file), status='old', &
         action='read', iostat=ierr, iomsg=iomsg)
    if (ierr /= 0) then
        write(*,'(A)') 'ERROR: cannot open configuration file: '//trim(config_file)
        write(*,'(A)') trim(iomsg)
        error stop 1
    end if

    rewind(io_unit)
    read(io_unit, nml=case_config, iostat=ierr, iomsg=iomsg)
    if (ierr /= 0) call namelist_error('case_config', iomsg)

    rewind(io_unit)
    read(io_unit, nml=reactor_config, iostat=ierr, iomsg=iomsg)
    if (ierr /= 0) call namelist_error('reactor_config', iomsg)

    rewind(io_unit)
    read(io_unit, nml=mixture_config, iostat=ierr, iomsg=iomsg)
    if (ierr /= 0) call namelist_error('mixture_config', iomsg)

    rewind(io_unit)
    read(io_unit, nml=physics_config, iostat=ierr, iomsg=iomsg)
    if (ierr /= 0) call namelist_error('physics_config', iomsg)

    rewind(io_unit)
    read(io_unit, nml=run_control_config, iostat=ierr, iomsg=iomsg)
    if (ierr /= 0) call namelist_error('run_control_config', iomsg)

    rewind(io_unit)
    read(io_unit, nml=output_config, iostat=ierr, iomsg=iomsg)
    if (ierr /= 0) call namelist_error('output_config', iomsg)
    close(io_unit)

    call normalize_and_validate_configuration()
    call resolve_mechanism()
    call resolve_solver()

    ! H2 + nu O2 + (N2/O2)*nu N2.
    nu = (100.0_dp - hydrogen_mole_percent) / hydrogen_mole_percent / &
         (1.0_dp + n2_o2_molar_ratio)
    phi = 0.5_dp / nu
    domain_length = real(cells_number_x,dp)*cell_length_x

    !--------------------------------------------------------------------------
    ! Deterministic, strict case directory creation.
    !--------------------------------------------------------------------------
    work_dir = trim(results_root)//trim(fold_sep)//trim(campaign_id)// &
               trim(fold_sep)//trim(case_directory)

    call make_case_directory_strict(trim(results_root), trim(campaign_id), &
                                    trim(work_dir))
    call copy_task_setup(trim(work_dir))
    call copy_configuration(trim(config_file), trim(work_dir))
    call change_directory(trim(work_dir))

    !--------------------------------------------------------------------------
    ! Run lifetime is owned by run_control, not data_io.
    !--------------------------------------------------------------------------
    select case(trim(termination_mode))
    case('simulation_time')
        problem_run_control = run_control_c( &
            termination_mode = 'simulation_time', &
            final_time       = final_time_ms*1.0e-3_dp)
    case('wall_time')
        problem_run_control = run_control_c( &
            termination_mode  = 'wall_time', &
            wall_time_limit   = wall_time_limit_s, &
            wall_time_reserve = wall_time_reserve_s)
    case('either')
        problem_run_control = run_control_c( &
            termination_mode  = 'either', &
            final_time        = final_time_ms*1.0e-3_dp, &
            wall_time_limit   = wall_time_limit_s, &
            wall_time_reserve = wall_time_reserve_s)
    case default
        error stop 'ERROR: unsupported termination_mode after validation.'
    end select

    !--------------------------------------------------------------------------
    ! Minimal uniform spatial surrogate of a homogeneous 0D reactor.
    !--------------------------------------------------------------------------
    problem_domain = computational_domain_c( &
        dimensions        = 1, &
        cells_number      = (/cells_number_x,1,1/), &
        coordinate_system = 'cartesian', &
        lengths           = reshape((/0.0_dp,0.0_dp,0.0_dp, &
                                      domain_length,cell_length_x,cell_length_x/), &
                                    (/3,2/)), &
        axis_names        = (/'x','y','z'/))

    !--------------------------------------------------------------------------
    ! Chemistry and thermodynamics.
    !--------------------------------------------------------------------------
    problem_chemistry = chemical_properties_c( &
        chemical_mechanism_file_name  = trim(mech_file), &
        default_enhanced_efficiencies = 1.0_dp, &
        E_act_units                   = 'cal.mol')

    problem_thermophysics = thermophysical_properties_c( &
        chemistry                   = problem_chemistry, &
        thermo_data_file_name       = trim(thermo_file), &
        transport_data_file_name    = trim(transdata_file), &
        molar_masses_data_file_name = 'molar_masses.dat')

    problem_mpi_support = mpi_communications_c(problem_domain)

    ! Transport properties are instantiated for NRG resource compatibility but
    ! transport mechanisms are disabled in this homogeneous adiabatic 0D reactor.
    ! Hydrodynamics is retained so each CFD solver advances its native equations.
    problem_solver_options = solver_options_c( &
        solver_name                  = trim(solver_name), &
        hydrodynamics_flag           = .true., &
        heat_transfer_flag           = .false., &
        molecular_diffusion_flag     = .false., &
        viscosity_flag               = .false., &
        thermal_radiation_flag       = .false., &
        soret_diffusion_flag         = .false., &
        chemical_reaction_flag       = .true., &
        grav_acc                     = (/0.0_dp,0.0_dp,0.0_dp/), &
        additional_particles_phases = 0, &
        CFL_flag                     = cfl_enabled, &
        CFL_coefficient              = cfl_coefficient, &
        initial_time_step            = initial_time_step)

    problem_data_manager = data_manager_c( &
        problem_domain, problem_mpi_support, problem_chemistry, &
        problem_thermophysics, problem_solver_options)

    call problem_data_manager%create_boundary_conditions( &
        problem_boundaries, number_of_boundary_types=1, default_boundary=1)
    call problem_data_manager%create_computational_mesh(problem_mesh)

    call problem_data_manager%create_scalar_field(p, 'pressure', 'p')
    call problem_data_manager%create_scalar_field(T, 'temperature', 'T')
    call problem_data_manager%create_scalar_field(rho, 'density', 'rho')
    call problem_data_manager%create_vector_field(v, 'velocity', 'v', 'spatial')
    call problem_data_manager%create_vector_field( &
        Y, 'specie_mass_fraction', 'Y', 'chemical')

    utter_loop = problem_domain%get_global_utter_cells_bounds()
    inner_loop = problem_domain%get_global_inner_cells_bounds()

    !--------------------------------------------------------------------------
    ! Uniform initial state. Composition is authored in mole units and converted
    ! once to normalized species mass fractions.
    !--------------------------------------------------------------------------
    T%cells(:,:,:) = initial_temperature
    p%cells(:,:,:) = initial_pressure
    do spec = 1, size(v%pr)
        v%pr(spec)%cells(:,:,:) = 0.0_dp
    end do
    do spec = 1, problem_chemistry%species_number
        Y%pr(spec)%cells(:,:,:) = 0.0_dp
    end do

    h2_index = problem_chemistry%get_chemical_specie_index('H2')
    o2_index = problem_chemistry%get_chemical_specie_index('O2')
    n2_index = problem_chemistry%get_chemical_specie_index('N2')
    if (min(h2_index,o2_index,n2_index) <= 0) then
        error stop 'ERROR: selected mechanism must contain H2, O2 and N2.'
    end if

    Y%pr(h2_index)%cells(:,:,:) = 1.0_dp
    Y%pr(o2_index)%cells(:,:,:) = nu
    Y%pr(n2_index)%cells(:,:,:) = nu*n2_o2_molar_ratio
    call problem_thermophysics%change_field_units_mole_to_dimless(Y)

    ! Closed, adiabatic, slip walls on both active-domain ends.
    call problem_boundaries%create_boundary_type( &
        type_name               = 'wall', &
        slip                    = .true., &
        conductive              = .false., &
        wall_temperature        = 0.0_dp, &
        wall_conductivity_ratio = 0.0_dp, &
        priority                = 1)

    problem_boundaries%bc_markers(utter_loop(1,1),:,:) = 1
    problem_boundaries%bc_markers(utter_loop(1,2),:,:) = 1

    !--------------------------------------------------------------------------
    ! Complete reactor history. Data-manager syntax resolves vector components
    ! such as specie_mass_fraction(H2) to scalar projections before processing.
    !--------------------------------------------------------------------------
    transducer_cell = 1
    transducer_cell(1) = (inner_loop(1,1) + inner_loop(1,2))/2
    transducer_area(:,1) = transducer_cell
    transducer_area(:,2) = transducer_cell

    operations_number = 3 + problem_chemistry%species_number
    problem_post_proc_manager = post_processor_manager_c( &
        problem_data_manager, number_post_processors=1)

    call problem_post_proc_manager%create_post_processor( &
        problem_data_manager, post_processor_name='reactor_history', &
        operations_number=operations_number, &
        save_time=postprocess_interval_us, save_time_units='microseconds')

    call problem_post_proc_manager%create_post_processor_operation( &
        problem_data_manager, 1, 'temperature', 'transducer', &
        operation_area=transducer_area)
    ! The first operation establishes the leading/transducer point. Subsequent
    ! operations use zero relative distance, which is the native NRG pattern for
    ! sampling several scalar observables at exactly the same point.
    call problem_post_proc_manager%create_post_processor_operation( &
        problem_data_manager, 1, 'pressure', 'transducer', &
        operation_area_distance=(/0,0,0/))
    call problem_post_proc_manager%create_post_processor_operation( &
        problem_data_manager, 1, 'density', 'transducer', &
        operation_area_distance=(/0,0,0/))

    do spec = 1, problem_chemistry%species_number
        specie_name = trim(problem_chemistry%species_names(spec))
        field_name = 'specie_mass_fraction('//trim(specie_name)//')'
        if (len_trim(field_name) > 40) then
            write(*,'(A,A)') 'ERROR: postprocessor field name is too long: ', &
                trim(field_name)
            error stop 9
        end if
        call problem_post_proc_manager%create_post_processor_operation( &
            problem_data_manager, 1, trim(field_name), 'transducer', &
            operation_area_distance=(/0,0,0/))
    end do

    ! Spatial snapshots are primarily a validation diagnostic for the 0D
    ! surrogate. When disabled, only forced initial/final saves are expected.
    if (save_spatial_fields) then
        effective_field_save_interval = field_save_interval_us
    else
        effective_field_save_interval = 1.0e30_dp
    end if

    problem_data_save = data_save_c( &
        problem_data_manager, &
        visible_fields_names=[character(len=40) :: &
            'pressure', 'temperature', 'density', 'velocity', &
            'specie_mass_fraction'], &
        save_time        = effective_field_save_interval, &
        save_time_units  = 'microseconds', &
        save_format      = 'tecplot', &
        data_save_folder = 'data_save', &
        debug_flag       = .false.)

    ! data_io is restart serialization only while run_control is active.
    problem_data_io = data_io_c( &
        problem_data_manager, &
        check_time         = checkpoint_interval_us, &
        check_time_units   = 'microseconds', &
        data_output_folder = 'data_output')

    !--------------------------------------------------------------------------
    ! Human-readable metadata.
    !--------------------------------------------------------------------------
    open(newunit=log_unit, file=problem_setup_log_file, &
         status='replace', form='formatted', action='write')
    write(log_unit,'(A)') 'Homogeneous H2-air constant-volume ignition case'
    write(log_unit,'(A,A)') 'Case ID: ', trim(case_id)
    write(log_unit,'(A,A)') 'Case fingerprint: ', trim(case_fingerprint)
    write(log_unit,'(A,A)') 'Case directory: ', trim(case_directory)
    write(log_unit,'(A,A)') 'Campaign ID: ', trim(campaign_id)
    write(log_unit,'(A,A)') 'Numerical variant: ', trim(numerical_variant)
    write(log_unit,'(A,A)') 'Reactor type: ', trim(reactor_type)
    write(log_unit,'(A,I0)') 'Computational cells: ', cells_number_x
    write(log_unit,'(A,ES14.6)') 'Cell length [m]: ', cell_length_x
    write(log_unit,'(A,ES14.6)') 'Initial temperature [K]: ', initial_temperature
    write(log_unit,'(A,ES14.6)') 'Initial pressure [Pa]: ', initial_pressure
    write(log_unit,'(A,F12.6)') 'Initial H2 mole percent: ', hydrogen_mole_percent
    write(log_unit,'(A,F12.6)') 'Equivalence ratio: ', phi
    write(log_unit,'(A,A)') 'Chemical mechanism: ', trim(mechanism_name)
    write(log_unit,'(A,A)') 'Thermodynamic database: ', trim(thermo_file)
    write(log_unit,'(A,A)') 'Transport database: ', trim(transdata_file)    
    write(log_unit,'(A,A)') 'Solver: ', trim(solver_name)
    write(log_unit,'(A,ES14.6)') 'Initial time step [s]: ', initial_time_step
    write(log_unit,'(A,A)') 'Termination mode: ', trim(termination_mode)
    write(log_unit,'(A,I0)') 'Reactor-history operations: ', operations_number
    write(log_unit,'(A)') 'History: T, p, rho and every mechanism species mass fraction.'
    write(log_unit,'(A)') 'Transport, viscosity, radiation and gravity are disabled.'
    write(log_unit,'(A)') 'Spatial snapshots are used to verify homogeneity of the CFD surrogate.'
    write(log_unit,'(A)') repeat('-',72)
    close(log_unit)

    call write_case_info()

    call problem_data_io%output_all_data(0.0_dp, stop_flag, make_output=.true.)
    call problem_data_save%save_all_data(0.0_dp, stop_flag, make_save=.true.)

    write(*,'(A)') 'Case generated successfully: '//trim(work_dir)

contains

    subroutine write_case_info()
        integer :: info_unit, species_index
        real(dp) :: x_h2, x_o2, x_n2

        x_h2 = hydrogen_mole_percent/100.0_dp
        x_o2 = (1.0_dp-x_h2)/(1.0_dp+n2_o2_molar_ratio)
        x_n2 = n2_o2_molar_ratio*x_o2

        open(newunit=info_unit, file='case_info.txt', status='replace', &
             form='formatted', action='write')

        write(info_unit,'(A)') '0D CONSTANT-VOLUME IGNITION CASE'
        write(info_unit,'(A)') repeat('=',72)
        write(info_unit,'(A,A)') 'Case ID: ', trim(case_id)
        write(info_unit,'(A,A)') 'Case fingerprint: ', trim(case_fingerprint)
        write(info_unit,'(A,A)') 'Directory: ', trim(case_directory)
        write(info_unit,'(A,A)') 'Campaign: ', trim(campaign_id)
        write(info_unit,'(A,A)') 'Numerical variant: ', trim(numerical_variant)
        if (len_trim(case_label) > 0) &
            write(info_unit,'(A,A)') 'Description: ', trim(case_label)
        write(info_unit,'(A)') ''

        write(info_unit,'(A)') 'REACTOR'
        write(info_unit,'(A)') repeat('-',72)
        write(info_unit,'(A,A)') 'Type: ', trim(reactor_type)
        write(info_unit,'(A,I0)') 'Cells: ', cells_number_x
        write(info_unit,'(A,ES16.8)') 'Cell length [m]: ', cell_length_x
        write(info_unit,'(A,ES16.8)') 'Domain length [m]: ', domain_length
        write(info_unit,'(A)') 'Boundary: closed, adiabatic, slip'
        write(info_unit,'(A)') ''

        write(info_unit,'(A)') 'INITIAL STATE'
        write(info_unit,'(A)') repeat('-',72)
        write(info_unit,'(A,F12.3)') 'Temperature [K]: ', initial_temperature
        write(info_unit,'(A,ES16.8)') 'Pressure [Pa]: ', initial_pressure
        write(info_unit,'(A,F12.6)') 'H2 [mole %]: ', hydrogen_mole_percent
        write(info_unit,'(A,F12.8)') 'X_H2: ', x_h2
        write(info_unit,'(A,F12.8)') 'X_O2: ', x_o2
        write(info_unit,'(A,F12.8)') 'X_N2: ', x_n2
        write(info_unit,'(A,F12.6)') 'Equivalence ratio: ', phi
        write(info_unit,'(A)') ''

        write(info_unit,'(A)') 'CHEMISTRY / NUMERICS'
        write(info_unit,'(A)') repeat('-',72)
        write(info_unit,'(A,A)') 'Mechanism: ', trim(mechanism_name)
        write(info_unit,'(A,A)') 'Solver: ', trim(solver_name)
        write(info_unit,'(A,ES16.8)') 'Initial time step [s]: ', initial_time_step
        write(info_unit,'(A,L1)') 'CFL enabled: ', cfl_enabled
        write(info_unit,'(A,F10.4)') 'CFL coefficient: ', cfl_coefficient
        write(info_unit,'(A,I0)') 'Species count: ', problem_chemistry%species_number
        write(info_unit,'(A)',advance='no') 'Species: '
        do species_index = 1, problem_chemistry%species_number
            if (species_index > 1) write(info_unit,'(A)',advance='no') ', '
            write(info_unit,'(A)',advance='no') &
                trim(problem_chemistry%species_names(species_index))
        end do
        write(info_unit,'(A)') ''
        write(info_unit,'(A)') ''

        write(info_unit,'(A)') 'RUN CONTROL / OUTPUT'
        write(info_unit,'(A)') repeat('-',72)
        write(info_unit,'(A,A)') 'Termination mode: ', trim(termination_mode)
        if (trim(termination_mode) == 'simulation_time' .or. &
            trim(termination_mode) == 'either') then
            write(info_unit,'(A,F12.6)') 'Final simulation time [ms]: ', final_time_ms
        end if
        if (trim(termination_mode) == 'wall_time' .or. &
            trim(termination_mode) == 'either') then
            write(info_unit,'(A,F12.3)') 'Wall-time limit [s]: ', wall_time_limit_s
            write(info_unit,'(A,F12.3)') 'Wall-time reserve [s]: ', wall_time_reserve_s
        end if
        write(info_unit,'(A,F12.6)') 'History interval [us]: ', postprocess_interval_us
        write(info_unit,'(A,F12.6)') 'Field-save interval [us]: ', field_save_interval_us
        write(info_unit,'(A,F12.6)') 'Restart check interval [us]: ', checkpoint_interval_us
        write(info_unit,'(A,L1)') 'Regular spatial snapshots: ', save_spatial_fields
        write(info_unit,'(A)') ''

        write(info_unit,'(A)') 'MACHINE-READABLE OUTPUT'
        write(info_unit,'(A)') repeat('-',72)
        write(info_unit,'(A)') 'reactor_history.dat : raw NRG transducer history'
        write(info_unit,'(A)') 'run_control_status.inf : NRG termination status'
        write(info_unit,'(A)') 'run_status.json : campaign-runner execution status'
        write(info_unit,'(A)') 'setup_input.nml : immutable case specification'

        close(info_unit)
    end subroutine write_case_info


    subroutine namelist_error(group_name, message)
        character(len=*), intent(in) :: group_name, message
        write(*,'(A,A)') 'ERROR reading namelist /', trim(group_name)//'/'
        write(*,'(A)') trim(message)
        error stop 2
    end subroutine namelist_error


    subroutine normalize_and_validate_configuration()
        case_id          = adjustl(case_id)
        case_fingerprint = to_lower_ascii(adjustl(case_fingerprint))
        case_directory   = adjustl(case_directory)
        case_label       = adjustl(case_label)
        campaign_id      = adjustl(campaign_id)
        results_root     = adjustl(results_root)
        numerical_variant = adjustl(numerical_variant)

        reactor_type     = to_lower_ascii(adjustl(reactor_type))
        mechanism_id     = to_lower_ascii(adjustl(mechanism_id))
        solver_id        = to_lower_ascii(adjustl(solver_id))
        termination_mode = to_lower_ascii(adjustl(termination_mode))

        if (len_trim(case_directory) == 0) case_directory = case_id
        call validate_id(case_id, 'case_id')
        call validate_fingerprint(case_fingerprint)
        call validate_id(case_directory, 'case_directory')
        call validate_id(campaign_id, 'campaign_id')

        if (trim(reactor_type) /= 'constant_volume') then
            error stop "ERROR: reactor_type must be 'constant_volume' in this interface."
        end if
        if (cells_number_x /= 2 .and. cells_number_x /= 4) then
            error stop 'ERROR: cells_number_x must be 2 or 4 for the 0D surrogate.'
        end if
        if (cell_length_x <= 0.0_dp) then
            error stop 'ERROR: cell_length_x must be positive.'
        end if
        if (hydrogen_mole_percent <= 0.0_dp .or. &
            hydrogen_mole_percent >= 100.0_dp) then
            error stop 'ERROR: hydrogen_mole_percent must lie in (0,100).'
        end if
        if (n2_o2_molar_ratio <= 0.0_dp) then
            error stop 'ERROR: n2_o2_molar_ratio must be positive.'
        end if
        if (initial_temperature <= 0.0_dp .or. initial_pressure <= 0.0_dp) then
            error stop 'ERROR: initial temperature and pressure must be positive.'
        end if
        if (initial_time_step <= 0.0_dp) then
            error stop 'ERROR: initial_time_step must be positive.'
        end if
        if (cfl_coefficient <= 0.0_dp .or. cfl_coefficient > 1.0_dp) then
            error stop 'ERROR: cfl_coefficient must lie in (0,1].'
        end if
        if (postprocess_interval_us <= 0.0_dp .or. &
            field_save_interval_us <= 0.0_dp .or. &
            checkpoint_interval_us <= 0.0_dp) then
            error stop 'ERROR: all output intervals must be positive.'
        end if

        select case(trim(termination_mode))
        case('simulation_time')
            if (final_time_ms <= 0.0_dp) then
                error stop 'ERROR: final_time_ms must be positive.'
            end if
        case('wall_time')
            call validate_wall_time_settings()
        case('either')
            if (final_time_ms <= 0.0_dp) then
                error stop 'ERROR: final_time_ms must be positive.'
            end if
            call validate_wall_time_settings()
        case default
            error stop &
                "ERROR: termination_mode must be 'simulation_time', 'wall_time' or 'either'."
        end select
        
        thermo_data_file    = adjustl(thermo_data_file)
        transport_data_file = adjustl(transport_data_file)

        if (len_trim(thermo_data_file) == 0) then
            error stop 'ERROR: thermo_data_file may not be empty.'
        end if

        if (len_trim(transport_data_file) == 0) then
            error stop 'ERROR: transport_data_file may not be empty.'
        end if
    end subroutine normalize_and_validate_configuration


    subroutine resolve_mechanism()
        select case(trim(mechanism_id))
        case('keromnes')
            mechanism_name = 'KEROMNES'
            mech_file = 'KEROMNES.txt'

        case('konnov')
            mechanism_name = 'KONNOV'
            mech_file = 'KONNOV.txt'

        case('zhang')
            mechanism_name = 'ZHANG'
            mech_file = 'ZHANG.txt'

        case('gerasimov_shatalov2013')
            mechanism_name = 'GERASIMOV_SHATALOV_2013'
            mech_file = 'GERASIMOV_SHATALOV_2013_NRG_noREV.txt'

        case('popov2007')
            mechanism_name = 'POPOV_2007'
            mech_file = 'POPOV_2007_H2_O2_NRG.txt'

        case('maas_pope1992')
            mechanism_name = 'MAAS_POPE_1992'
            mech_file = 'MAAS_POPE_1992_H2_NRG_noREV.txt'

        case('li2004')
            mechanism_name = 'LI_2004'
            mech_file = 'LI_ZHAO_KAZAKOV_DRYER_2004_checked_N2.txt'

        case('williams2004')
            mechanism_name = 'WILLIAMS_2004'
            mech_file = 'WILLIAMS_2004.txt'
            
        case('gri_mech3')
            mechanism_name = 'GRI_MECH3'
            mech_file = 'GRI_MECH_3_H2_checked_original.txt'
            
        case('tereza')
            mechanism_name = 'TEREZA'
            mech_file = 'TEREZA_orig.txt'
            
        case('hong2010')
            mechanism_name = 'HONG_2010'
            mech_file = 'HONG_2010_TABLE7_checked.txt'
                                      
        case default
            write(*,'(A,A)') 'ERROR: unsupported mechanism_id: ', trim(mechanism_id)
            error stop 3
        end select
        
        
!        mech_file      = trim(mechanism_name)//'.txt'
!        thermo_file    = trim(mechanism_name)//'_THERMO.txt'
!        transdata_file = trim(mechanism_name)//'_TRANSDATA.txt'
        
        thermo_file    = trim(thermo_data_file)
        transdata_file = trim(transport_data_file)
    end subroutine resolve_mechanism


    subroutine resolve_solver()
        select case(trim(solver_id))
        case('cpm')
            solver_name = 'cpm'
        case('cabaret','cabaret_compressible')
            solver_name = 'CABARET'
        case('cabaret_low_mach','cabaret_lm')
            solver_name = 'CABARET_low_mach'
        case('fds','fds_low_mach')
            solver_name = 'fds_low_mach'
        case default
            write(*,'(A,A)') 'ERROR: unsupported solver_id: ', trim(solver_id)
            error stop 4
        end select
    end subroutine resolve_solver


    subroutine validate_id(value, label)
        character(len=*), intent(in) :: value, label
        if (len_trim(value) == 0) then
            write(*,'(A,A)') 'ERROR: empty identifier: ', trim(label)
            error stop 5
        end if
        if (index(value,'..') /= 0 .or. index(value,'/') /= 0 .or. &
            index(value,achar(92)) /= 0 .or. index(value,':') /= 0) then
            write(*,'(A,A)') 'ERROR: path characters are not allowed in ', trim(label)
            error stop 5
        end if
    end subroutine validate_id


    subroutine validate_fingerprint(value)
        character(len=*), intent(in) :: value
        integer :: idx, code
        if (len_trim(value) /= 32) then
            error stop 'ERROR: case_fingerprint must contain 32 hexadecimal characters.'
        end if
        do idx = 1, len_trim(value)
            code = iachar(value(idx:idx))
            if (.not. ((code >= iachar('0') .and. code <= iachar('9')) .or. &
                       (code >= iachar('a') .and. code <= iachar('f')))) then
                error stop 'ERROR: case_fingerprint is not lowercase hexadecimal.'
            end if
        end do
    end subroutine validate_fingerprint


    subroutine validate_wall_time_settings()
        if (wall_time_limit_s <= 0.0_dp) then
            error stop 'ERROR: wall_time_limit_s must be positive.'
        end if
        if (wall_time_reserve_s < 0.0_dp .or. &
            wall_time_reserve_s >= wall_time_limit_s) then
            error stop &
                'ERROR: wall_time_reserve_s must be nonnegative and smaller than wall_time_limit_s.'
        end if
    end subroutine validate_wall_time_settings


    subroutine make_case_directory_strict(root, campaign, path)
        character(len=*), intent(in) :: root, campaign, path
        character(len=1024) :: parent_path

        parent_path = trim(root)//trim(fold_sep)//trim(campaign)
#ifdef WIN
        command = 'if not exist "'//trim(root)//'" mkdir "'//trim(root)//'"'
        call run_command_checked(command, 'create results root')
        command = 'if not exist "'//trim(parent_path)//'" mkdir "'// &
                  trim(parent_path)//'"'
        call run_command_checked(command, 'create campaign directory')
        command = 'mkdir "'//trim(path)//'"'
#else
        command = 'mkdir -p "'//trim(parent_path)//'"'
        call run_command_checked(command, 'create campaign directory')
        command = 'mkdir "'//trim(path)//'"'
#endif
        call run_command_checked(command, 'create new case directory')
    end subroutine make_case_directory_strict


    subroutine copy_task_setup(path)
        character(len=*), intent(in) :: path
#ifdef WIN
        command = 'xcopy "'//trim(task_setup_folder)//'" "'//trim(path)// &
                  trim(fold_sep)//trim(task_setup_folder)//'" /E /I /K /Y >NUL'
#else
        command = 'cp -a "'//trim(task_setup_folder)//'" "'//trim(path)// &
                  trim(fold_sep)//'"'
#endif
        call run_command_checked(command, 'copy task_setup directory')
    end subroutine copy_task_setup


    subroutine copy_configuration(source_file, path)
        character(len=*), intent(in) :: source_file, path
#ifdef WIN
        command = 'copy /Y "'//trim(source_file)//'" "'//trim(path)// &
                  trim(fold_sep)//'setup_input.nml" >NUL'
#else
        command = 'cp "'//trim(source_file)//'" "'//trim(path)// &
                  trim(fold_sep)//'setup_input.nml"'
#endif
        call run_command_checked(command, 'copy setup input')
    end subroutine copy_configuration


    subroutine run_command_checked(cmd, description)
        character(len=*), intent(in) :: cmd, description
        command_status = 0
        exit_status = 0
        iomsg = ''
        call execute_command_line(trim(cmd), wait=.true., &
            cmdstat=command_status, exitstat=exit_status, cmdmsg=iomsg)
        if (command_status /= 0 .or. exit_status /= 0) then
            write(*,'(A)') 'ERROR: failed to '//trim(description)
            write(*,'(A)') 'Command: '//trim(cmd)
            if (len_trim(iomsg) > 0) write(*,'(A)') trim(iomsg)
            write(*,'(A,I0,A,I0)') 'cmdstat=', command_status, &
                                    ', exitstat=', exit_status
            error stop 7
        end if
    end subroutine run_command_checked


    subroutine change_directory(path)
        character(len=*), intent(in) :: path
        character(kind=c_char), allocatable :: c_path(:)
        integer(c_int) :: status
        integer :: n, idx

        n = len_trim(path)
        allocate(c_path(0:n))
        do idx = 1, n
            c_path(idx-1) = path(idx:idx)
        end do
        c_path(n) = c_null_char
        status = c_chdir(c_path)
        deallocate(c_path)
        if (status /= 0_c_int) then
            write(*,'(A,A)') 'ERROR: cannot change directory to ', trim(path)
            error stop 8
        end if
    end subroutine change_directory


    pure function to_lower_ascii(value) result(lower_value)
        character(len=*), intent(in) :: value
        character(len=len(value)) :: lower_value
        integer :: idx, code

        lower_value = value
        do idx = 1, len(value)
            code = iachar(lower_value(idx:idx))
            if (code >= iachar('A') .and. code <= iachar('Z')) then
                lower_value(idx:idx) = achar( &
                    code + iachar('a') - iachar('A'))
            end if
        end do
    end function to_lower_ascii

end program package_interface
